### ISSUE TITLE
Make it playable on GitHub Pages at sdku.piyo.cafe

### ISSUE THREAD

**Issue by raviriley** [lanpai/sdku#1]
tutorial:
https://medium.com/the-andela-way/how-to-deploy-your-react-application-to-github-pages-in-less-than-5-minutes-8c5f665a2d2a

corresponding repo:
https://github.com/seunzone/TD-React-Challenge-Test-1/tree/master

add a CNAME record in ur repo and DNS records for the subdomain

I want to play it! lol

**Comment by lanpai** [comment]
Its playable right now at https://lanpai.github.io/sdku/ but sure I can add my custom domain
